export const CREATE_COURSE = 'CREATE_COURSE';
export const LOAD_RESOURCESUBJECT_SUCCESS = 'LOAD_RESOURCESUBJECT_SUCCESS';
export const LOAD_RESOURCES_SUCCESS = 'LOAD_RESOURCES_SUCCESS';
export const CREATE_REVIEW_SUCCESS = 'CREATE_REVIEW_SUCCESS';
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS';
export const TOGGLE_CAN_DELETE_SUCCESS = 'TOGGLE_CAN_DELETE_SUCCESS';
